### ISSUE TITLE
Failed to build scs ERROR: Could not build wheels for scs which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by gurusura** [ssantoshp/Empyrial#25] opened 2021-06-29 15:39 UTC
I am using Python 3.8.10.
I had a separate environment and I got the following error when pip installing empyrial
Failed to build scs
ERROR: Could not build wheels for scs which use PEP 517 and cannot be installed directly

From this link https://github.com/pydata/bottleneck/issues/281
I tried pip install --upgrade pip setuptools wheel  but I am still getting the same bug when installing empyrial.

 - OS: Ubuntu 20.04
- mini conda version and a separate environment for trading
- Python 3.8.10
- Let me know if there is any way around this bug. 
Thanks

**Comment by gurusura** [comment] 2021-06-29 15:48
It seems to work in a fresh environment with Python 3.9.5 though.

**Comment by ssantoshp** [comment] 2021-06-29 15:50
Hey!

That's because one of the dependencies of Empyrial is PyPortfolioOpt and it uses PEP 517. There are two ways to deal with that:

1) If you absolutely need to download Empyrial locally:

You'll have to follow the installation process given here: https://pypi.org/project/pyportfolioopt/

And you can see the prerequisites:

![image](https://user-images.githubusercontent.com/61618641/123828323-ab799a00-d901-11eb-9ad8-a470ccdb1457.png)

That's certainly the origin of your problem. Personally, I'm on Windows so the problem was that I didn't install C++ tools with [Visual Studio](https://visualstudio.microsoft.com/downloads/)

2) If you're like me, a slacker who likes to put off his duties until later

Just go and ```pip install empyrial``` on [Google Colab](https://colab.research.google.com/notebooks/intro.ipynb?hl=fr#recent=true). Works like a charm!

Let me know how it goes!

Best,

**Comment by gurusura** [comment] 2021-06-29 16:12
Did successfully install in a fresh environment, but still unable to run your first command

from empyrial import empyrial, Engine

portfolio = Engine(    
                  start_date= "2018-06-09", 
                  portfolio= ["BABA", "RELIANCE.NS", "KO", "^DJI","^IXIC"], 
                  weights = [0.2, 0.2, 0.2, 0.2, 0.2], #equal weighting by default
                  benchmark = ["SPY"] #SPY by default
)

empyrial(portfolio)


---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-6e5674835e53> in <module>
----> 1 from empyrial import empyrial,Engine

ModuleNotFoundError: No module named 'empyrial'

**Comment by gurusura** [comment] 2021-06-29 16:14
> Hey!
> 
> That's because one of the dependencies of Empyrial is PyPortfolioOpt and it uses PEP 517. There are two ways to deal with that:
> 
> 1. If you absolutely need to download Empyrial locally:
> 
> You'll have to follow the installation process given here: https://pypi.org/project/pyportfolioopt/
> 
> And you can see the prerequisites:
> 
> ![image](https://user-images.githubusercontent.com/61618641/123828323-ab799a00-d901-11eb-9ad8-a470ccdb1457.png)
> 
> That's certainly the origin of your problem. Personally, I'm on Windows so the problem was that I didn't install C++ tools with [Visual Studio](https://visualstudio.microsoft.com/downloads/). I installed it and then it worked! So since you're on OS, (I never tried yet but I know some Empyrial's users use OS), you'll maybe have to install the Command-line tools (I have no idea what that is but you will all the info on the link I sent you).
> 
> 1. If you're like me, a slacker who likes to put off his duties until later
> 
> Just go and `pip install empyrial` on [Google Colab](https://colab.research.google.com/notebooks/intro.ipynb?hl=fr#recent=true). Works like a charm!
> 
> Let me know how it goes!
> 
> Best,

Will try this. Thanks

**Comment by ssantoshp** [comment] 2021-06-29 16:21
> Did successfully install in a fresh environment, but still unable to run your first command


Hmm... strange, I tried it again and it works fine as you can see here: https://colab.research.google.com/drive/1RgND0uWNUE0WhQcLd2KXYW1OKo7xjA0C?usp=sharing

So, the problem is not with the code, are you sure Empyrial is correctly installed?
You can check that by running ```pip list``` in the command prompt in the current directory and check if you can find Empyrial on this list.
Here the problem is that it doesn't detect Empyrial, as it wasn't installed. 

Is it really important for you to use Empyrial locally? Honestly, google collab is very straightforward and will save you time.

**Comment by gurusura** [comment] 2021-06-29 16:22
Tried my portfolio using your library. Works like a charm. Will play with it more. I would like to test it in my ubuntu too, not just collab. I will try using the pyportfolio link you have given. Thanks for the quick response. 
Great work. 
Best

**Comment by ssantoshp** [comment] 2021-06-29 16:27
> Tried my portfolio using your library. Works like a charm. 

Thank you! I hope you like it, I am currently working on better documentation of Empyrial. Let me know how it goes for Ubuntu, never tried this one. 

We are also working on making Empyrial a software so really anyone (without a programming background) would you use it.

You're welcome and also if you have any feature request/discussion you can check our forum [here](https://github.com/ssantoshp/Empyrial/discussions) =)

If it's fine for you, we can close this issue, have a good day.

**Closed** 2021-06-29 18:13 UTC

**Comment by gurusura** [comment] 2021-06-29 19:21
Sure
